version: '2'

services:
        usvn:
                container_name: tracsvn_usvn

                dns_search:
                        - 172.18.0.1

                build: ../

                ports:
                        - "80:80"
                        - "443:443"
                links:
                        - "mysql:usvn_db"

        mysql:
                container_name: tracsvn_mysql

                image: "mysql:latest"

                volumes:
                        - "./data_svn/BDD-USVN:/usvn.sql" #exporting existing database for manual importation

                expose:
                        - "3306"

                environment:
                        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                        - MYSQL_USER=${MYSQL_USER}
                        - MYSQL_DATABASE=${MYSQL_DATABASE}
                        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
